#!/bin/bash

pipeline {
	agent {
		label 'slave1'
	} 

	stages {
	    stage('Checkout') {
	        steps {
			checkout scm			       
		      }}
		stage('Build') {
	           steps {
			   sh 'JAVA_HOME=/home/gamut/Distros/jdk1.8.0_191 /home/gamut/Distros/apache-maven-3.6.0/bin/mvn install'
	                 }}
		stage('Deployment'){
		    steps {
		            sh 'sshpass -p "gamut" scp /home/gamut/build/workspace/jenkins_pipeline_slave/target/gamutkart.war gamut@172.17.0.3:/home/gamut/Distros/apache-tomcat-8.5.35/webapps'
			  }}
	}
}
